version: "3.9"

services:
  db:
    image: postgres:16
    container_name: open_meteo_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etl_code/sql_script/init.sql:/docker-entrypoint-initdb.d/init.sql

  etl:
    build:
      context: .
    container_name: open_meteo_etl
    depends_on:
      - db
    environment:
      DB_USER: users
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: database
      START_DATE: "2025-05-16"
      END_DATE: "2025-05-30"
    command: python etl_code/main.py

volumes:
  postgres_data:
